# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IJSPhotoSDKProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IJSPhotoSDKProject

 pod 'MLeaksFinder', '~> 0.2.1'

end
